name: Style check

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  flake8_py3:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install flake8 and plugins
        run: |
          pip install flake8 flake8-docstrings flake8-annotations

      - name: Configure Flake8
        run: |
          echo "[flake8]" > .flake8
          echo "extend-ignore = E402" >> .flake8
          echo "exclude = .github" >> .flake8
          echo "enable-extensions = ANN002,ANN003,ANN201,ANN202,ANN203,ANN204,ANN205,ANN206,ANN401,ANN402,D101,D102,D103,D104,D105,D106,D107" >> .flake8

      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: "flake8_py3"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
